steps:
- label: "Kubectl version :congratulations: :champagne:"
  agents:
    queue: default-queue
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef: { name: yer-private-git-ssh-key }
        podSpec:
          containers:
            - image: alpine/k8s:1.27.5
              command: [kubectl]
              args:
                - "version"
                - "--short"
              resources:
                limits:
                  cpu: "100m"
                  memory: "128Mi"
